### ISSUE TITLE
Todo List

### ISSUE THREAD

**Issue by hansputera** [hansputera/hestia#1]
- [x] Use MongoDB as database (~~votings~~, and attendance)
- [ ] Create voting (vote name, vote desc, vote duration (secs, mins, hours, days, or weeks), admin voteable, vote count maximum)
- [x] Voting (by reply, just reply the message with option number or the option name)
- [ ] Vote end (vote queue number)
- [ ] Attendance (just reply to a message with a reason that must be longer than 10 characters to be the reason for permission)
- [ ] Homework helper (QAnda, Brainly, Math solver, Roboguru, Zenius Blog, Colearn, etc..)

**Comment by hansputera** [comment]
Additional feature:
- [x] Admin Groups (to show admins who are in this group)
